---
deployment:
  tasks:
    - export DEPLOYPATH=/home/digyata/public_html/
    - /bin/cp -r resources $DEPLOYPATH
    - /bin/cp -r routes $DEPLOYPATH
    - /bin/cp -r app $DEPLOYPATH
    - /bin/cp -r public $DEPLOYPATH
    
